### ISSUE TITLE
Issue when executing the sniffy.py

### ISSUE THREAD

**Issue by 1nf1n7y** [kbrebanov/sniffy#2]
Traceback (most recent call last):
  File "sniffy.py", line 5, in <module>
    import sniffer.sniffer as sniffer
  File "/root/Desktop/sniffy/sniffer/sniffer.py", line 3, in <module>
    import pcappy
  File "/usr/local/lib/python3.6/dist-packages/pcappy/__init__.py", line 10, in <module>
    from functions import *
ModuleNotFoundError: No module named 'functions'

**Comment by kbrebanov** [comment]
I have not used or maintained this code in a while, but from the traceback you posted, it looks like an error with the pcappy module.
